### ISSUE TITLE
goodpractice removed from CRAN

### ISSUE THREAD

**Issue by dpprdan** [MangoTheCat/goodpractice#154]
From https://cran.r-project.org/package=goodpractice:

> Package ‘goodpractice’ was removed from the CRAN repository.
> 
> Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/goodpractice).
> 
> Archived on 2022-04-27 as check issues were not corrected in time.
> 
> A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2022/2022-04-27_check_results_goodpractice.html).

From a quick look at the check results I'd say that the error might be loosely related to #135/#136, but I might be wrong. Are you still familiar with this @russHyde?

**Comment by hfrick** [comment]
thanks for this @dpprdan! I handed maintainership over to other people at Mango but this didn't get on CRAN.

@ddbortoli you're listed as the new maintainer in #151 - are there any plans to get goodpractice back on CRAN? 🙏

**Comment by ddbortoli** [comment]
thanks for flagging this up, both! I will look into properly updating the package maintainership over the next few days and getting this back into CRAN.

**Comment by mccroweyclinton-EPA** [comment]
Hello do you have an ETA for when this package will be back on CRAN?

**Comment by ddbortoli** [comment]
goodpractice `v1.0.3` has been submitted to CRAN a few hours ago. Hopefully it should be back online in not too long!

**Comment by hfrick** [comment]
Looks like goodpractice is not yet back on CRAN - @anasimmons @ddbortoli let me know if you need me to email CRAN about the maintainer change.

**Comment by ddbortoli** [comment]
> Looks like goodpractice is not yet back on CRAN - @anasimmons @ddbortoli let me know if you need me to email CRAN about the maintainer change.

Thanks for the offer! Yeah, it's taking a while - we haven't heard anything from them yet. From what I'm reading online, we don't normally need to message CRAN about changing maintainer on an archived package, but given it's taking so long that might help moving things along.
Could you please do that then? And do let me / @anasimmons know if there's anything else we can help with!

**Comment by hfrick** [comment]
@anasimmons @ddbortoli goodpractice is not on the CRAN incoming server https://r-hub.github.io/cransays/articles/dashboard.html Could you resubmit, please? 🙏

**Comment by ddbortoli** [comment]
> @anasimmons @ddbortoli goodpractice is not on the CRAN incoming server https://r-hub.github.io/cransays/articles/dashboard.html Could you resubmit, please? 🙏

huh, that's interesting, somehow it fell through the cracks. That's actually not bad, since after making the previous submission I realised something: the [failed test results](https://cran-archive.r-project.org/web/checks/2022/2022-04-27_check_results_goodpractice.html#:~:text=failed_checks(g)%0A%C2%A0%C2%A0%C2%A0%C2%A0Error%20in%20is.na(chk)%20%7C%7C%20(%22status%22%20%25in%25%20names(chk)%20%26%26%20is.na(chk%5B%5B%22status%22%5D%5D))%20%3A%0A%C2%A0%C2%A0%C2%A0%C2%A0%20%27length%20%3D%202%27%20in%20coercion%20to%20%27logical(1)%27) on some Unix flavours are due to [some changes in R-devel](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html#:~:text=Calling%20%26%26%20or,to%20%27logical(1)%27).

So we'll fix that then resubmit!

**Comment by mccroweyclinton-EPA** [comment]
Can someone please give an updated ETA for this package? I am unable to push updates to my package until all of it's dependencies, including goodpractice is available on CRAN. Can someone please comminicate what is going on? This has been held up for over two months.
