### ISSUE TITLE
Suggestion: produce more output for Travis

### ISSUE THREAD

**Issue by richelbilderbeek** [MangoTheCat/goodpractice#23]
When I run `Rscript -e 'goodpractice::gp()'` on a package I want to be tested by Travis, the build sometimes terminates as `rcmdcheck` takes longer than 10 minutes (from [this build log](https://travis-ci.org/richelbilderbeek/Cer2016/builds/148868896)):

```
Preparing: rcmdcheck

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

It is possible to let Travis allow for more than ten minutes of silence, but I'd suggest to let `rcmdcheck` produce more output.

**Comment by gaborcsardi** [comment]
:+1:

**Comment by gaborcsardi** [comment]
OK, I am thinking about this. Not so easy to do properly, because I run `R CMD check` and `covr`, which might take a long time, and I cannot easily show a progress bar for them.

I think for now I'll just show their output on the screen. Not so nice, but better than seeing that nothing is happening.

**Comment by richelbilderbeek** [comment]
Sounds like a superior solution than a timed-out build to me :+1:

**Comment by gaborcsardi** [comment]
OK, there is a quiet option now, set it to `FALSE`: 

```r
gp(..., quiet = FALSE)
```

**Comment by richelbilderbeek** [comment]
Great work, thanks!
